import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar-components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="flex fle-col">
        <Navbar
          navLinks={[
            { href: "/dashboard", name: "Dashboard" },
            { href: "/", name: "Home" },
            { href: "/account", name: "Account" },
          ]}
        />
        <body className={inter.className}>{children}</body>
      </div>
    </html>
  );
}
